map $http_upgrade $lingdian_connection_upgrade {
    default upgrade;
    '' close;
}

server {
    listen 80;
    listen [::]:80;
    server_name app.zsf.shopping;
    location / { proxy_pass http://127.0.0.1:8082; include /etc/nginx/proxy_params; }
    location /api/ { proxy_pass http://127.0.0.1:9000; include /etc/nginx/proxy_params; }
}

server {
    listen 80;
    listen [::]:80;
    server_name merchant.zsf.shopping;
    location / { proxy_pass http://127.0.0.1:8083; include /etc/nginx/proxy_params; }
    location /api/ { proxy_pass http://127.0.0.1:9000; include /etc/nginx/proxy_params; }
}

server {
    listen 80;
    listen [::]:80;
    server_name admin.zsf.shopping;
    location / { proxy_pass http://127.0.0.1:8084; include /etc/nginx/proxy_params; }
    location /api/ { proxy_pass http://127.0.0.1:9000; include /etc/nginx/proxy_params; }
}

server {
    listen 80;
    listen [::]:80;
    server_name api.zsf.shopping;
    client_max_body_size 20m;
    location / {
        proxy_pass http://127.0.0.1:9000;
        include /etc/nginx/proxy_params;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $lingdian_connection_upgrade;
    }
}

