<script setup lang="ts">
import type { AuthRole, PlatformUserQuery, PlatformUserStatus, PlatformUserSummary } from '@lingdian/contracts'
import { onMounted, reactive, ref } from 'vue'
import { listUsers } from '../../services/admin-users'
const query = reactive<PlatformUserQuery>({ page: 1, pageSize: 20 }); const users = ref<PlatformUserSummary[]>([]); const total = ref(0); const loading = ref(false); const error = ref('')
const roleLabels: Record<AuthRole, string> = { SUPER_ADMIN: '超级管理员', ADMIN: '管理员', MERCHANT: '商家', USER: '普通用户' }
async function load() { loading.value = true; error.value = ''; try { const page = await listUsers(query); users.value = page.items; total.value = page.total } catch (cause) { error.value = cause instanceof Error ? cause.message : '用户加载失败' } finally { loading.value = false } }
function search() { query.page = 1; void load() }
onMounted(() => void load())
</script>
<template><div class="page-stack"><div class="page-heading"><div><h1>用户管理</h1><p>统一查看和管理全平台账号、角色与状态。</p></div><el-button type="primary">新建用户</el-button></div><el-card shadow="never"><el-form class="filter-form" inline @submit.prevent="search"><el-form-item label="关键词"><el-input v-model="query.keyword" clearable placeholder="昵称 / 账号 / 手机号" /></el-form-item><el-form-item label="角色"><el-select v-model="query.role" clearable placeholder="全部角色"><el-option v-for="(label, value) in roleLabels" :key="value" :label="label" :value="value" /></el-select></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable placeholder="全部状态"><el-option label="正常" value="ACTIVE" /><el-option label="已停用" value="DISABLED" /></el-select></el-form-item><el-form-item><el-button type="primary" @click="search">查询</el-button><el-button @click="Object.assign(query, { keyword: undefined, role: undefined as AuthRole | undefined, status: undefined as PlatformUserStatus | undefined, page: 1 }); load()">重置</el-button></el-form-item></el-form></el-card><el-alert v-if="error" :title="error" type="error" show-icon :closable="false"><template #default><el-button link type="danger" @click="load">重试</el-button></template></el-alert><el-card class="table-card" shadow="never"><el-table v-loading="loading" :data="users" row-key="userId"><el-table-column label="用户" min-width="190"><template #default="{ row }"><div class="identity-cell"><el-avatar>{{ (row.nickname || row.username || '用').slice(0, 1) }}</el-avatar><div><strong>{{ row.nickname || '未设置昵称' }}</strong><small>{{ row.username || '无账号' }}</small></div></div></template></el-table-column><el-table-column prop="phone" label="手机号" min-width="145" /><el-table-column label="角色" min-width="180"><template #default="{ row }"><el-tag v-for="role in row.roles" :key="role" class="role-tag" effect="plain">{{ roleLabels[role as AuthRole] }}</el-tag></template></el-table-column><el-table-column label="门店范围" min-width="150"><template #default="{ row }">{{ row.storeIds.length ? `${row.storeIds.length} 个门店` : '—' }}</template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="row.status === 'ACTIVE' ? 'success' : 'info'">{{ row.status === 'ACTIVE' ? '正常' : '已停用' }}</el-tag></template></el-table-column><el-table-column label="最近登录" min-width="170"><template #default="{ row }">{{ row.lastLoginAt ? new Date(row.lastLoginAt).toLocaleString() : '从未登录' }}</template></el-table-column><el-table-column label="操作" fixed="right" width="170"><template #default><el-button link type="primary">编辑</el-button><el-button link>重置密码</el-button></template></el-table-column><template #empty><el-empty description="暂无符合条件的用户" /></template></el-table><div class="pagination"><el-pagination v-model:current-page="query.page" v-model:page-size="query.pageSize" layout="total, prev, pager, next" :total="total" @current-change="load" /></div></el-card></div></template>
